version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=music_user
      - DB_PASSWORD=music_password
      - DB_NAME=music_book
      - YOUTUBE_API_KEY=your_youtube_api_key
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      mysql:
        condition: service_healthy
      jaeger:
        condition: service_started
    networks:
      - music-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: music_book
      MYSQL_USER: music_user
      MYSQL_PASSWORD: music_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - music-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "music_user", "-pmusic_password"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    networks:
      - music-network

volumes:
  mysql_data:

networks:
  music-network:
    driver: bridge